library(tidyverse)
library(readxl)
library(readxlsx)
library(tidyquant)
library(stringr)
library(cellranger)
library(sf)
library(ggplot2)
library(leaflet)
library(raster)
library(dplyr)
library(spData)
library(tmap)
library(ggplot2)
library(shiny)
library(lubridate)

tabla <- read_xlsx("CostoPorTecnico.xlsx")


